# Generated by Django 4.0.2 on 2022-02-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shredApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_elevation', models.IntegerField()),
                ('peak_elevation', models.IntegerField()),
                ('price', models.IntegerField()),
                ('trails', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('airbnb', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentTrip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='riding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stance',
        ),
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ManyToManyField(to='shredApp.User'),
        ),
        migrations.AddField(
            model_name='resort',
            name='trips',
            field=models.ManyToManyField(to='shredApp.Trips'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shredApp.trips'),
        ),
    ]
