# Generated by Django 4.0.2 on 2022-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredApp', '0003_lodging_status_resort_pass_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='riding',
            field=models.CharField(choices=[('BRD', 'BOARD'), ('SKI', 'SKI')], default='BRD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='stance',
            field=models.CharField(choices=[('RG', 'REGULAR'), ('GF', 'GOOFY')], default='RG', max_length=3),
        ),
    ]
